### ISSUE TITLE
Mod worked fine but crashed after 5 hours

### ISSUE THREAD

**Issue by Reporrrtzsss** [MinectfzApk/Minecraft-Jenny-Mod-Mod-1.21.20.23-Unlimited-Items#2]
Hey the mod was working fine but suddenly it crashed what could be the reason?

**Comment by MinectfzApk** [comment]
> Hey the mod was working fine but suddenly it crashed what could be the reason?

hello , sorry for the issue , i have fixed it , it should be working now :)
